[package]
name = "scenario-1"
version = "0.1.0"
rust-version = "1.66.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["tcp-server", "tcp-client", "http_server", "http"]

[dependencies]
